# Settings
[custom]
playerCount = 1200
kickMessage = "&fDne &a9. 5. 2022 &fje &lSloCraft &fzaprl svoja vrata. \n\nHvala vsem, ki ste bili z nami na tej poti &c❤ \n\n&fVeč informacij na &ahttps://slocraft.eu"

[editions.java]
enabled = true

  [editions.java.config]
  onlineMode = false
  bind = "0.0.0.0:25565"
  bungeePluginChannelEnabled = false
  builtinCommands = false
  forceKeyAuthentication = false

    [editions.java.config.status]
      # Supports basic colors with & - https://mctools.org/motd-creator
      motd = "                  &c❤ &f&lSloCraft &c❤&r\n        &aZačetek konca ali konec začetka?"
      favicon = "slocraft-logo-64.png"
      announceForge = true
